FirstJoinMode: VANILLA

Formats:
  admin:
    priority: 10
    join:
      actions:
        - '[BROADCAST] &8(&a+&8) &c&lADMIN &f%player_name%'
        - '[SOUND] ENTITY_PLAYER_LEVELUP;10;5'
        - '[ACTIONBAR] &ashop.example.com;5'
        - '[JSON_MESSAGE] {"text":"&9Click to go to our discord","clickEvent":{"action":"open_url","value":"https://discord.gg/hPNYUMUauD"}}'
    quit:
      actions:
        - '[BROADCAST] &8(&c-&8) &f%player_name%'
  default:
    priority: 5
    join:
      actions:
        - '[BROADCAST] &8(&a+&8) &f%player_name%'
        - '[SOUND] ENTITY_PLAYER_LEVELUP;10;5'
        - '[ACTIONBAR] &ashop.example.com'
        - '[FIREWORK] STAR;10;2;255,120,200;100,50,30;10,20,30;40;10;20'
    quit:
      actions:
        - '[BROADCAST] &8(&c-&8) &f%player_name%'
